server:
   port: 8888
   
spring:
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
# 配置数据源类型
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/defend?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useTimezone=true&serverTimezone=UTC
      username: root
      password: 123qwe
# 初始化，最小，最大连接数
      initialSize: 5
      minidle: 5
      maxActive: 25
# 获取数据库连接等待的超时时间
      maxWait: 60000
# 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: SELECT 1 FROM dual
      
mybatis:
   type-aliases-package: com.blt.entity
   mapper-locations: classpath:mappers/**.xml
   check-config-location: true
   configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# page helper
pagehelper:
   helperDialect: mysql
   reasonable: false
   supportMethodsArguments: true
   params: count=countSql